"use client";

import { ArrowDown, ArrowRight, Check, Copy, ExternalLink, Leaf, Menu, ShieldCheck, Users, X } from "lucide-react";
import { useState } from "react";

const CONTRACT = "0x652BCA0b212D133490b5736781FA847318841230";
const basescan = `https://basescan.org/token/${CONTRACT}`;

export function BubbleBackground() {
  return <div aria-hidden className="pointer-events-none fixed inset-0 overflow-hidden opacity-60"><div className="absolute -left-32 top-32 h-72 w-72 rounded-full bg-olive-700/20 blur-3xl" /><div className="absolute right-0 top-1/3 h-96 w-96 rounded-full bg-gold/10 blur-3xl" /><div className="absolute bottom-0 left-1/3 h-80 w-80 rounded-full bg-olive-600/20 blur-3xl" /></div>;
}

export function Navbar() {
  const [open, setOpen] = useState(false);
  const links = [["Hakkımızda", "about"], ["Sistem", "system"], ["Yol Haritası", "roadmap"], ["Token", "token"], ["İletişim", "contact"]];
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-olive-900/80 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><a href="#top" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-gold/60 bg-olive-800 text-gold"><Leaf size={20} /></span><span className="font-serif text-lg font-semibold tracking-wide">ZEYTİNDALI <span className="text-gold">BZYT</span></span></a><button className="text-gold md:hidden" onClick={() => setOpen(!open)} aria-label="Menüyü aç">{open ? <X /> : <Menu />}</button><nav className={`${open ? "absolute left-0 right-0 top-full flex" : "hidden"} flex-col gap-5 border-b border-white/10 bg-olive-900 px-6 py-6 md:static md:flex md:flex-row md:border-0 md:bg-transparent md:p-0`}>{links.map(([label, id]) => <a key={id} onClick={() => setOpen(false)} className="text-sm text-white/70 transition hover:text-gold" href={`#${id}`}>{label}</a>)}<a href={basescan} target="_blank" rel="noreferrer" className="z-btn-primary py-2.5">Base Explorer <ExternalLink size={15} className="ml-2" /></a></nav></div></header>;
}

export function Hero() {
  return <section id="top" className="relative flex min-h-[760px] items-center overflow-hidden pt-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(74,124,89,.24),transparent_35%),linear-gradient(135deg,#0a1f0a_20%,#132d19_70%,#0a1f0a)]" /><div className="z-section grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">Base Network • Sürdürülebilirlik • Şeffaflık</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.05] text-white sm:text-7xl">İyilik, <span className="text-gold">üretimle</span> büyür.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">ZEYTİNDALI (BZYT), tarım ve hayvancılığın gerçek değerini blockchain şeffaflığıyla buluşturan, insanlık için tasarlanmış bir yardım vizyonudur.</p><div className="mt-9 flex flex-wrap gap-4"><a className="z-btn-primary" href="#about">Projeyi keşfet <ArrowRight size={17} className="ml-2" /></a><a className="z-btn-outline" href="#token">Token bilgileri</a></div><div className="mt-12 flex flex-wrap gap-8 text-sm text-white/55"><span><strong className="block text-2xl text-gold">%50</strong> Sosyal fayda</span><span><strong className="block text-2xl text-gold">%25</strong> Büyüme</span><span><strong className="block text-2xl text-gold">%25</strong> Topluluk</span></div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-6 rounded-full bg-gold/10 blur-3xl" /><div className="relative aspect-square rounded-[2.5rem] border border-gold/30 bg-gradient-to-br from-olive-700/80 to-olive-900 p-5 shadow-2xl shadow-black/40"><div className="flex h-full flex-col items-center justify-center rounded-[2rem] border border-gold/20 bg-olive-900/60 p-8 text-center"><div className="mb-6 grid h-36 w-36 place-items-center rounded-full border-2 border-gold/70 bg-olive-800 text-gold shadow-[0_0_60px_rgba(212,175,55,.18)]"><Leaf size={75} strokeWidth={1.25} /></div><p className="font-serif text-3xl text-white">Bir fikir.</p><p className="mt-1 font-serif text-3xl text-gold">Bir sistem.</p><p className="mt-6 text-sm uppercase tracking-[.22em] text-white/45">Biz gideriz, iyilik kalır.</p></div></div></div></div><a href="#about" aria-label="Aşağı kaydır" className="absolute bottom-8 left-1/2 -translate-x-1/2 text-gold/70"><ArrowDown className="animate-bounce" /></a></section>;
}

export function About() {
  return <section id="about" className="z-section"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Neden Zeytindalı?</p><h2 className="font-serif text-4xl leading-tight sm:text-5xl">İyilik, bir dilek değil; <span className="text-gold">işleyen bir düzen</span> olsun.</h2></div><div className="space-y-6 text-lg leading-8 text-white/65"><p>Zeytindalı, kurucusu Abdusselam Tokmakçı’nın üretim, şeffaflık ve insan onuru etrafında geliştirdiği bir sosyal sorumluluk vizyonudur.</p><p>Amacımız bağış toplamak değil; tarım ve hayvancılık faaliyetleriyle üretim yapan, kazancını adil bir dağılım modeliyle sosyal faydaya dönüştürmeyi hedefleyen sürdürülebilir bir yapı kurmaktır.</p><blockquote className="border-l-2 border-gold pl-6 font-serif text-2xl italic text-white">“Gerçek miras, insanlığa bırakılan iyiliktir.”</blockquote></div></div></section>;
}

export function System() {
  const cards = [{ icon: <Leaf />, title: "Üretim", text: "Tarım, hayvancılık ve katma değerli ürünlerle gerçek ekonomik faaliyet." }, { icon: <ShieldCheck />, title: "Şeffaflık", text: "Base ağı üzerinde doğrulanabilir kayıtlar ve izlenebilir kararlar." }, { icon: <Users />, title: "Dayanışma", text: "Üretimden doğan değeri ihtiyaç sahipleri ve toplulukla buluşturma hedefi." }];
  return <section id="system" className="z-section"><div className="mb-12 max-w-2xl"><p className="eyebrow">Nasıl çalışır?</p><h2 className="font-serif text-4xl sm:text-5xl">Teknoloji, <span className="text-gold">insanlık için.</span></h2><p className="mt-5 leading-7 text-white/60">Zeytindalı modeli; üretim, şeffaf kayıt ve topluluk katılımını aynı çatı altında buluşturmayı hedefler.</p></div><div className="grid gap-5 md:grid-cols-3">{cards.map((card) => <div key={card.title} className="glass rounded-2xl p-7 transition hover:-translate-y-1 hover:border-gold/30"><div className="mb-6 grid h-12 w-12 place-items-center rounded-xl bg-gold/10 text-gold">{card.icon}</div><h3 className="font-serif text-2xl text-white">{card.title}</h3><p className="mt-3 leading-7 text-white/55">{card.text}</p></div>)}</div></section>;
}

export function Roadmap() {
  const items = [["01", "Fikir ve temel", "Vizyonun, marka kimliğinin ve blockchain altyapısının hazırlanması."], ["02", "İlk üretim", "Türkiye’de tarım ve hayvancılık için pilot üretim modelinin geliştirilmesi."], ["03", "Şeffaf büyüme", "Ürün, gelir ve sosyal fayda verilerinin toplulukla paylaşılması."], ["04", "Dünya için bir dal", "Modelin farklı coğrafyalarda uygulanabilir hale gelmesi." ]];
  return <section id="roadmap" className="z-section"><div className="mb-12"><p className="eyebrow">Yol haritası</p><h2 className="font-serif text-4xl sm:text-5xl">Adım adım, <span className="text-gold">gerçek değer.</span></h2></div><div className="grid gap-4 md:grid-cols-4">{items.map(([no, title, text], i) => <div key={no} className="relative rounded-2xl border border-white/10 bg-white/[.03] p-6"><span className="font-serif text-4xl text-gold/50">{no}</span><h3 className="mt-8 text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{text}</p>{i < 3 && <div className="absolute -right-3 top-1/2 hidden text-gold md:block"><ArrowRight size={18} /></div>}</div>)}</div></section>;
}

export function Whitepaper() {
  return <section id="whitepaper" className="z-section"><div className="glass flex flex-col items-start justify-between gap-8 rounded-3xl p-8 sm:p-12 md:flex-row md:items-center"><div><p className="eyebrow">Teknik doküman</p><h2 className="font-serif text-3xl sm:text-4xl">Vizyonu daha yakından inceleyin.</h2><p className="mt-4 max-w-2xl leading-7 text-white/60">Projenin amacı, token dağılımı ve blockchain yaklaşımı whitepaper dokümanında açıklanır.</p></div><a className="z-btn-primary whitespace-nowrap" href="/whitepaper.pdf" target="_blank" rel="noreferrer">Whitepaper <ExternalLink size={16} className="ml-2" /></a></div></section>;
}

export function Contact() {
  return <section id="contact" className="z-section"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">Topluluğa katılın</p><h2 className="font-serif text-4xl sm:text-5xl">Birlikte daha <span className="text-gold">iyi</span> bir gelecek.</h2><p className="mt-5 max-w-xl leading-7 text-white/60">Sorularınız, iş birlikleri ve proje hakkında daha fazla bilgi için bizimle iletişime geçin.</p></div><div className="glass rounded-2xl p-7"><div className="space-y-5 text-sm"><a className="flex items-center justify-between border-b pb-4 text-white/70 hover:text-gold" href="mailto:tokmakcisames@gmail.com">E-posta <span>tokmakcisames@gmail.com</span></a><a className="flex items-center justify-between border-b pb-4 text-white/70 hover:text-gold" href="https://t.me/Samed1981" target="_blank" rel="noreferrer">Telegram <span>@Samed1981</span></a><a className="flex items-center justify-between text-white/70 hover:text-gold" href="https://www.instagram.com/tokmakcisamet" target="_blank" rel="noreferrer">Instagram <span>@tokmakcisamet</span></a></div></div></div></section>;
}

export function TokenInfo() {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(CONTRACT); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  return <section id="token" className="z-section"><div className="rounded-3xl border border-gold/25 bg-gradient-to-br from-olive-800/70 to-olive-900 p-8 sm:p-12"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">Token bilgileri</p><h2 className="font-serif text-4xl">ZEYTİNDALI <span className="text-gold">(BZYT)</span></h2><p className="mt-4 max-w-xl text-white/60">Base Network üzerinde çalışan proje tokeni.</p></div><a className="z-btn-outline" href={basescan} target="_blank" rel="noreferrer">BaseScan’de görüntüle <ExternalLink size={15} className="ml-2" /></a></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-black/20 p-5"><p className="text-xs uppercase tracking-widest text-white/45">Arz</p><p className="mt-2 text-xl font-semibold text-white">1,000,000,000</p></div><div className="rounded-xl bg-black/20 p-5"><p className="text-xs uppercase tracking-widest text-white/45">Ağ</p><p className="mt-2 text-xl font-semibold text-white">Base</p></div><div className="rounded-xl bg-black/20 p-5"><p className="text-xs uppercase tracking-widest text-white/45">Kurucu</p><p className="mt-2 text-xl font-semibold text-white">Abdusselam Tokmakçı</p></div></div><button onClick={copy} className="mt-6 flex max-w-full items-center gap-3 break-all rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-left text-xs text-white/60 hover:border-gold/40"><span>{CONTRACT}</span>{copied ? <Check size={16} className="shrink-0 text-gold" /> : <Copy size={16} className="shrink-0 text-gold" />}</button></div></section>;
}

export function Footer() { return <footer className="relative z-10 border-t border-white/10 px-6 py-10"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-4 text-sm text-white/45 sm:flex-row"><p>© {new Date().getFullYear()} ZEYTİNDALI BZYT</p><p>Üretimden doğan değer, insanlığa dokunsun.</p></div></footer>; }
